services:
  films:
    image: 'postgres:15.4'
    build: films
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=db_user'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=base_de_donnee_des_films'
  voyageurs:
    image: 'postgres:15.4'
    build: voyageurs
    ports:
      - '5435:5432'
    environment:
      - 'POSTGRES_USER=db_user'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=base_de_donnee_des_voyageurs'
  cours:
    image: 'postgres:15.4'
    build: films
    ports:
      - '5436:5432'
    environment:
      - 'POSTGRES_USER=db_user'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=base_de_donnee_cours_de_langue'